name: Build (Java - Maven)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      - name: Build with Maven
        run: ./mvnw -B -DskipTests clean package
